import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import "./globals.css";

const inter = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Snap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" type="image/png" sizes="32x32" href="./images/logo.svg" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
